### ISSUE TITLE
Loop sending "isready" and "stop" commands when using Lc0

### ISSUE THREAD

**Issue by Virinas-code** [lichess-org/external-engine#15]
### Setup

I installed external-engine via the debsource. I modified the config to use lc0 as engine. Lc0 uses the CPU network file, with standard configuration.

### Problem

After searching on a position, it continues sending `isready` and `stop` commands. It filled my log files (total 40 Go) and broke my root partition.

**Comment by niklasf** [comment]
Can you please recheck this with the latest version? There's not yet a new Debian package, currently just a Python script.
