### ISSUE TITLE
Stockfish eating up RAM after being used

### ISSUE THREAD

**Issue by SandaruKasa** [lichess-org/external-engine#17]
I have remote-uci and stockfish installed from AUR to my laptop (because non-external engine on the analysis board only detects 1 out of my 12 CPU cores). This installation includes a systemd service for the remote uci (and a socket too). After having used https://lichess.org/analysis with the external engine, stockfish ends up hanging in the background with all the memory that has been allocated to it.

I have to `sudo systemctl stop remote-uci.service` or `sudo pkill stockfish` if I want to get my RAM back (or, alternatively, go back to the analysis board, and turn engine's memory slider all the way down to 16MB or so).

I have tried different approaches to make the engine stop on its own: closing the tab instead of closing the browser, going to another lichess page, refreshing, turning evaluation off, disconnecting from the remote engine. Nothing seems to help.

I'm not sure whether this is actually an issue or it's just me using the software in an unintended way. Also not sure whether this should go to lila issues or here (and whether the inaccurate detection for the number of CPU cores is a lila issue or just a browser limitation).

**Comment by niklasf** [comment]
This is working as expected, but definitely something that needs to be changed.
