### ISSUE TITLE
Authorization url uses wrong ip address

### ISSUE THREAD

**Issue by jonbbbb** [lichess-org/external-engine#19]
After running the docker script on Windows, the url it produces is:
`https://lichess.org/analysis/external?url=ws%3A%2F%2F0.0.0.0%3A9670%2Fsocket&secret=redacted&name=Stockfish+15&maxThreads=8&maxHash=8192`

The 0.0.0.0 value doesn't work. Manually changing it to 127.0.0.1 fixes it.

**Comment by niklasf** [comment]
Thanks for reporting. Closing, because this new API design solves this.
