### ISSUE TITLE
External engines: random errors coming up

### ISSUE THREAD

**Issue by Juesto** [lichess-org/external-engine#35]
after `example-provider.py` terminates the idle engine i receive `TypeError: network error`
sometimes often i get a error status 503 either randomly or after a moment of an attempted startup
no errors in the python output, also tried lichess-tauri and it has the same 503 symptoms and has no logging

**Comment by schlawg** [comment]
![image](https://github.com/lichess-org/external-engine/assets/101470903/31accf33-b35a-4940-9e2a-c5fc00901d62)

The dialog for 503s has been improved. We're blaming this one on Juesto's VPN.

**Comment by Juesto** [comment]
> The dialog for 503s has been improved. We're blaming this one on Juesto's VPN.

lol, i guess my connection was spotty and the external engine didn't really connect.
thanks for the improvement however
