### ISSUE TITLE
Consider renaming `example-provider.py`

### ISSUE THREAD

**Issue by cyqsimon** [lichess-org/external-engine#36]
The current name is a bit confusing because `example` implies that the script shouldn't be used without modification, which isn't really the case. I think a name like `local-provider.py` or `delegate-provider.py` may be more appropriate.

**Comment by Juesto** [comment]
the file is meant to be a working example, however, utilizing it directly as-is is implied to be not intended for production use.
this repository is meant for developers to fork and port the example or modify it for their needs.

**Comment by niklasf** [comment]
https://github.com/fitztrev/lichess-tauri is intended to be a production-grade client.

**Comment by Juesto** [comment]
@niklasf sorry for mentioning but it would've been more accurate to close it as not planned imo

**Comment by niklasf** [comment]
Sorry, still often forget that's an option.
