### ISSUE TITLE
finding binaries / version string

### ISSUE THREAD

**Issue by vondele** [lichess-org/external-engine#5]
some observations of a first test. after installing with
```
echo 'deb [arch=amd64 trusted=yes] https://lichess-org.github.io/external-engine/debian bullseye main' | sudo tee /etc/apt/sources.list.d/external-engine.list
sudo apt update
sudo apt install remote-uci stockfish
```
and enabling with `http://localhost:9670/` I noticed that the external engine was shown as stockfish 12 not stockfish 15. It turned out that the external engine found was an old one in `/usr/local/bin/stockfish` and not the freshly installed one in `/usr/bin/stockfish`. Probably because of the order of these directories in the PATH. Not sure this needs or can be fixed easily.

After removing the `/usr/local/bin/stockfish` (now having `/usr/bin/stockfish` found with `which`), the label shown on the web page was still `stockfish 12`, probably not updated. I think this got fixed after installing/reinstalling remote-uci and visiting `http://localhost:9670/` again. Maybe the version check could be done at always.

**Comment by niklasf** [comment]
Thanks for testing!

I temporarily reduced this repo to a more minimal example provider. It updates the meta data on every startup. Will have to keep this in mind for a more fully-featured provider as well.
